name: 'Dispatch command'

on:
  issue_comment:
    types: [ created ]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: myparcelnl/actions/setup-git-credentials@v3
        id: credentials
        with:
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}
          app-id: ${{ secrets.MYPARCEL_APP_ID }}

      - uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ steps.credentials.outputs.token }}
          commands: rebase
          permission: write
          issue-type: pull-request
