name: 'Release new version'

on:
  push:
    branches:
      - main

  workflow_dispatch: ~

jobs:
  release:
    name: 'Build and publish 🚀'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: myparcelnl/actions/yarn-install@v2

      - uses: myparcelnl/actions/semantic-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_REPO_TOKEN }}

      - uses: myparcelnl/actions/rebase@v2
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}
          base: main
          target: develop

  rebase:
    name: 'Rebase develop onto main'
    needs: release
    if: always()
    uses: myparcelnl/magento/.github/workflows/rebase.yml@main
    secrets: inherit
    with:
      base: main
      target: develop

  rebase-prs:
    name: 'Rebase pull requests onto develop'
    needs: rebase
    runs-on: ubuntu-20.04
    steps:
      - uses: peter-evans/rebase@v2
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}
          base: develop
          exclude-drafts: true
          exclude-labels: 'hotfix'
